<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSMAgaiw\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSMAgaiw/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSMAgaiw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSMAgaiw\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerSMAgaiw\srcApp_KernelProdContainer([
    'container.build_hash' => 'SMAgaiw',
    'container.build_id' => '97a1cf5d',
    'container.build_time' => 1564234189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSMAgaiw');
