<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSBzK1q7\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSBzK1q7/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSBzK1q7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSBzK1q7\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerSBzK1q7\srcApp_KernelProdContainer([
    'container.build_hash' => 'SBzK1q7',
    'container.build_id' => '18e9184a',
    'container.build_time' => 1564571809,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSBzK1q7');
