<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_apicompte' => [[], ['_controller' => 'App\\Controller\\CompteController::index'], [], [['text', '/api/']], [], []],
    '_apishow_compte' => [['id'], ['_controller' => 'App\\Controller\\CompteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api']], [], []],
    '_apilist_compte' => [['page'], ['page' => '1', '_controller' => 'App\\Controller\\CompteController::list'], ['page' => '\\d+'], [['variable', '/', '\\d+', 'page', true], ['text', '/api']], [], []],
    '_apiadd_compte' => [[], ['_controller' => 'App\\Controller\\CompteController::Ajout'], [], [['text', '/api/compte']], [], []],
    'partenaire' => [[], ['_controller' => 'App\\Controller\\PartenaireController::index'], [], [['text', '/partenaire']], [], []],
    '_apitransaction' => [[], ['_controller' => 'App\\Controller\\TransactionController::index'], [], [['text', '/api/']], [], []],
    '_apiadd_transaction' => [[], ['_controller' => 'App\\Controller\\TransactionController::Ajout'], [], [['text', '/api/transaction']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/api/']], [], []],
    'add_user' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/user']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
];
