<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::Ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\CompteController::list' => ['privates', '.service_locator.AK4A8Fa', 'get_ServiceLocator_AK4A8FaService.php', true],
    'App\\Controller\\CompteController::show' => ['privates', '.service_locator.O0uin.n', 'get_ServiceLocator_O0uin_NService.php', true],
    'App\\Controller\\TransactionController::Ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\CompteController:Ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\CompteController:list' => ['privates', '.service_locator.AK4A8Fa', 'get_ServiceLocator_AK4A8FaService.php', true],
    'App\\Controller\\CompteController:show' => ['privates', '.service_locator.O0uin.n', 'get_ServiceLocator_O0uin_NService.php', true],
    'App\\Controller\\TransactionController:Ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\CompteController::Ajout' => '?',
    'App\\Controller\\CompteController::list' => '?',
    'App\\Controller\\CompteController::show' => '?',
    'App\\Controller\\TransactionController::Ajout' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\CompteController:Ajout' => '?',
    'App\\Controller\\CompteController:list' => '?',
    'App\\Controller\\CompteController:show' => '?',
    'App\\Controller\\TransactionController:Ajout' => '?',
    'App\\Controller\\UserController:register' => '?',
]));
