<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmM4G8q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmM4G8q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZmM4G8q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZmM4G8q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZmM4G8q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZmM4G8q',
    'container.build_id' => '2f092e91',
    'container.build_time' => 1564233775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmM4G8q');
