<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD6ZDHx4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD6ZDHx4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD6ZDHx4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD6ZDHx4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD6ZDHx4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D6ZDHx4',
    'container.build_id' => '2459bdb8',
    'container.build_time' => 1564423914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD6ZDHx4');
