<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Mq0qQx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Mq0qQx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Mq0qQx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Mq0qQx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7Mq0qQx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7Mq0qQx',
    'container.build_id' => '3bd59238',
    'container.build_time' => 1564329987,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Mq0qQx');
