<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RmVK4Lc' shared service.

return $this->privates['.service_locator.RmVK4Lc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::add' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\CompteController::list' => ['privates', '.service_locator.AK4A8Fa', 'get_ServiceLocator_AK4A8FaService.php', true],
    'App\\Controller\\CompteController::show' => ['privates', '.service_locator.O0uin.n', 'get_ServiceLocator_O0uin_NService.php', true],
    'App\\Controller\\DepotController::add' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController::add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\TransactionController::Ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UserController::adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\CompteController:add' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\CompteController:list' => ['privates', '.service_locator.AK4A8Fa', 'get_ServiceLocator_AK4A8FaService.php', true],
    'App\\Controller\\CompteController:show' => ['privates', '.service_locator.O0uin.n', 'get_ServiceLocator_O0uin_NService.php', true],
    'App\\Controller\\DepotController:add' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController:add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\TransactionController:Ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UserController:adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\CompteController::add' => '?',
    'App\\Controller\\CompteController::list' => '?',
    'App\\Controller\\CompteController::show' => '?',
    'App\\Controller\\DepotController::add' => '?',
    'App\\Controller\\PartenaireController::add' => '?',
    'App\\Controller\\TransactionController::Ajout' => '?',
    'App\\Controller\\UserController::adduser' => '?',
    'App\\Controller\\CompteController:add' => '?',
    'App\\Controller\\CompteController:list' => '?',
    'App\\Controller\\CompteController:show' => '?',
    'App\\Controller\\DepotController:add' => '?',
    'App\\Controller\\PartenaireController:add' => '?',
    'App\\Controller\\TransactionController:Ajout' => '?',
    'App\\Controller\\UserController:adduser' => '?',
]);
