<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UG8jfOt' shared service.

return $this->privates['.service_locator.UG8jfOt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::addcompte' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController::addDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::addPartenaire' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController::list' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\PartenaireController::updatePartenaire' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\TransactionController::addTransaction' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\TransactionController::list' => ['privates', '.service_locator.k6pF5Cm', 'get_ServiceLocator_K6pF5CmService.php', true],
    'App\\Controller\\TransactionController::show' => ['privates', '.service_locator.fmbWqv.', 'get_ServiceLocator_FmbWqv_Service.php', true],
    'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\CompteController:addcompte' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController:addDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:addPartenaire' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController:list' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\PartenaireController:updatePartenaire' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\TransactionController:addTransaction' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\TransactionController:list' => ['privates', '.service_locator.k6pF5Cm', 'get_ServiceLocator_K6pF5CmService.php', true],
    'App\\Controller\\TransactionController:show' => ['privates', '.service_locator.fmbWqv.', 'get_ServiceLocator_FmbWqv_Service.php', true],
    'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\CompteController::addcompte' => '?',
    'App\\Controller\\DepotController::addDepot' => '?',
    'App\\Controller\\PartenaireController::addPartenaire' => '?',
    'App\\Controller\\PartenaireController::list' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\PartenaireController::updatePartenaire' => '?',
    'App\\Controller\\TransactionController::addTransaction' => '?',
    'App\\Controller\\TransactionController::list' => '?',
    'App\\Controller\\TransactionController::show' => '?',
    'App\\Controller\\UserController::addUser' => '?',
    'App\\Controller\\CompteController:addcompte' => '?',
    'App\\Controller\\DepotController:addDepot' => '?',
    'App\\Controller\\PartenaireController:addPartenaire' => '?',
    'App\\Controller\\PartenaireController:list' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\PartenaireController:updatePartenaire' => '?',
    'App\\Controller\\TransactionController:addTransaction' => '?',
    'App\\Controller\\TransactionController:list' => '?',
    'App\\Controller\\TransactionController:show' => '?',
    'App\\Controller\\UserController:addUser' => '?',
]);
