<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fmbWqv.' shared service.

return $this->privates['.service_locator.fmbWqv.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'transaction' => ['privates', '.errored..service_locator.fmbWqv..App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.fmbWqv.": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
], [
    'serializer' => '?',
    'transaction' => 'App\\Entity\\Transaction',
    'transactionRepository' => 'App\\Repository\\TransactionRepository',
]);
